[workspace]
authors = ["sudh29 <sudhanshuiet15@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Data-Structure-Code-Mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062105,<26"
